// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnyEShj_5MRqhLO9ADdrvOHRMjiOfgicY',
    appId: '1:611882127081:web:1d3716857f9813434daa78',
    messagingSenderId: '611882127081',
    projectId: 'phase01-14cd8',
    authDomain: 'phase01-14cd8.firebaseapp.com',
    storageBucket: 'phase01-14cd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsuFuWVNqHVoeTLB0TOfefzD2V1nZUMc',
    appId: '1:611882127081:android:e25045d7dde2a20c4daa78',
    messagingSenderId: '611882127081',
    projectId: 'phase01-14cd8',
    storageBucket: 'phase01-14cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-lOUr5CFn-hbYCWCX_QbI01_3jAzCbqY',
    appId: '1:611882127081:ios:a5effe20aa5f742e4daa78',
    messagingSenderId: '611882127081',
    projectId: 'phase01-14cd8',
    storageBucket: 'phase01-14cd8.appspot.com',
    iosBundleId: 'com.laurence.template01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-lOUr5CFn-hbYCWCX_QbI01_3jAzCbqY',
    appId: '1:611882127081:ios:a5effe20aa5f742e4daa78',
    messagingSenderId: '611882127081',
    projectId: 'phase01-14cd8',
    storageBucket: 'phase01-14cd8.appspot.com',
    iosBundleId: 'com.laurence.template01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnyEShj_5MRqhLO9ADdrvOHRMjiOfgicY',
    appId: '1:611882127081:web:00e02adc60ace0c14daa78',
    messagingSenderId: '611882127081',
    projectId: 'phase01-14cd8',
    authDomain: 'phase01-14cd8.firebaseapp.com',
    storageBucket: 'phase01-14cd8.appspot.com',
  );
}
